### ISSUE TITLE
Fedora tarballs do not contain package managers

### ISSUE THREAD

**Issue by hexchain** [nspawn/mkosi-definitions#1]
The fedora tarballs provided on nspawn.org do not have working package managers. There are no dnf/yum/rpm inside.

**Comment by shibumi** [comment]
Yes, this is something I have to have a look on.. I guess I just need to modify the post-install script for fedora and install dnf/yum/rpm manually. Funny that the mkosi team don't ship a package manager on default

**Comment by shibumi** [comment]
PRs are btw welcome ;)

**Comment by fmorato** [comment]
mkosi files seem to support installing packages, as in the file below:
https://github.com/systemd/mkosi/blob/master/mkosi.files/mkosi.fedora
```
# SPDX-License-Identifier: LGPL-2.1+
# Let's build an image that is just good enough to build new mkosi images again

[Distribution]
Distribution=fedora
Release=29

[Output]
Format=gpt_ext4
Bootable=yes
Output=fedora.raw

[Packages]
Packages=
        arch-install-scripts
        btrfs-progs
        debootstrap
        dnf
        dosfstools
        git-core
        gnupg
        squashfs-tools
        tar
        veritysetup
```

**Comment by shibumi** [comment]
Thanks a lot, I am generating new images right now..
