### ISSUE TITLE
Containers have no network

### ISSUE THREAD

**Issue by shibumi** [nspawn/mkosi-definitions#2]
All containers don't have network.. This is something I would expect, so I will add it.

**Comment by q2dg** [comment]
The problem is to decide which kind of network would be the most suitable to implement by default: --private-network, macvlan, ipvlan, etc...

**Comment by shibumi** [comment]
The containers should just have the regular `host` systemd-networkd interface. I don't really plan to have different network types like ipvlan, macvlan etc..

**Comment by Edu4rdSHL** [comment]
All the networking-related issues with containers have been fixed, now all of them work out-of-the-box and also include basic networking tools such as `ip` and `ping`.
